r"""I/O utilities for parsing opacity tables from various sources.

Opacity tables from various external sources are often necessary for astrophysical
applications. To avoid requiring users to utilize a specific table hard-coded onto the
Trilobite package, we provide various utilities for parsing opacity tables from different sources.

Once generated, these table can be fed into the correct opacity class corresponding to
the table format.

.. rubric:: Supported Table Formats

* **TOPS** — Los Alamos National Laboratory opacity tables generated by the
  TOPS opacity code (https://aphysics2.lanl.gov/).
"""

import re
from pathlib import Path
from types import SimpleNamespace
from typing import Union

import numpy as np

from trilobite.utils.log import trilobite_logger


def read_tops(path: Union[str, Path]) -> SimpleNamespace:
    r"""Parse a TOPS opacity text file into a namespace of physical arrays.

    TOPS is the Los Alamos National Laboratory Opacity Code, available at
    https://aphysics2.lanl.gov/.  This function reads the fixed-width text
    output produced by TOPS and returns both the Rosseland mean and Planck mean
    opacities on the native :math:`(T,\,\rho)` grid, along with the composition
    information embedded in the file header.

    Parameters
    ----------
    path : str or ~pathlib.Path
        Path to the TOPS output text file.

    Returns
    -------
    SimpleNamespace
        A read-only namespace with the following attributes:

        ``grid_T`` : ndarray, shape ``(n_T,)``, units :math:`\mathrm{K}`
            Temperature grid assembled from the data-block headers, converted
            from the native keV to Kelvin.
        ``grid_rho`` : ndarray, shape ``(n_rho,)``, units :math:`\mathrm{g\,cm^{-3}}`
            Density grid taken from the data block with the most density rows.
            Blocks with fewer rows are padded with ``NaN`` at positions not
            covered by that block.
        ``rosseland`` : ndarray, shape ``(n_T, n_rho)``, units :math:`\mathrm{cm^2\,g^{-1}}`
            Rosseland mean opacity. Entries with no valid data are ``NaN``.
        ``planck`` : ndarray, shape ``(n_T, n_rho)``, units :math:`\mathrm{cm^2\,g^{-1}}`
            Planck mean opacity.  Entries with no valid data are ``NaN``.
        ``n_free`` : ndarray, shape ``(n_T, n_rho)``
            Number of free electrons per atom.
        ``av_sq_free`` : ndarray, shape ``(n_T, n_rho)``
            Average squared number of free electrons per atom.
        ``elements`` : list of str
            Chemical symbols of the constituent elements.
        ``atomic_numbers`` : ndarray of int, shape ``(n_materials,)``
            Atomic number of each element.
        ``number_fractions`` : ndarray, shape ``(n_materials,)``
            Number (molar) fraction of each element.
        ``mass_fractions`` : ndarray, shape ``(n_materials,)``
            Mass fraction of each element.
        ``material_ids`` : ndarray of int, shape ``(n_materials,)``
            TOPS material identifier for each element.
        ``title`` : str
            Title string from the file header (e.g. ``"Solar"``).

    Notes
    -----
    TOPS output files list both the *full* table grid dimensions in the header
    (``Number of T``, ``Number of rho``) and the *actual* grids used for the
    current run.  The data blocks may cover only a subset of the listed
    temperature grid when some :math:`(T, \rho)` points fall outside the
    physical validity domain of the TOPS database.

    Density values that exceed the physical table boundary are *clamped* by
    TOPS to the nearest valid density; the clamped points are flagged in a
    ``WARNING`` block near the top of the file.  These rows appear in the data
    with repeated opacity values — callers that need to distinguish valid from
    clamped data should inspect plateau regions near the density boundaries.

    Temperature is stored internally by TOPS in keV; this function converts to
    Kelvin using the relation :math:`1\,\mathrm{keV} = 1.1604518 \times 10^7\,\mathrm{K}`.

    Examples
    --------
    .. code-block:: python

        from trilobite.radiation.opacity.opacity_io import (
            read_tops,
        )

        ns = read_tops("tables/tops_solar.txt")
        print(ns.grid_T)  # temperature grid in K
        print(ns.grid_rho)  # density grid in g/cm³
        print(ns.rosseland)  # shape (n_T, n_rho), cm² g⁻¹
    """
    from astropy.io import ascii as _asc

    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"TOPS file not found: {path!r}")

    trilobite_logger.debug("read_tops: opening %s", path)
    full_text = path.read_text()
    ALL_LINES = full_text.splitlines()
    NUM_LINES = len(ALL_LINES)

    def _read_indented_table(start, names):
        """Collect indented rows from ALL_LINES[start:] and parse with astropy."""
        rows, j = [], start
        while j < NUM_LINES and ALL_LINES[j].startswith(" ") and ALL_LINES[j].strip():
            rows.append(ALL_LINES[j])
            j += 1
        return _asc.read(rows, names=names), j

    # ---- Title ----
    m_title = re.search(r"TOPS results for\s+(.*?)\s+on\s+", full_text)
    title = m_title.group(1).strip() if m_title else ""
    trilobite_logger.debug("read_tops: title = %r", title)

    # ---- Composition ----
    # Search for the section header anywhere in the file, then skip the
    # column-header line and collect the indented data rows below it.
    # A missing or empty composition block is non-fatal: a warning is issued
    # and the composition fields are set to None.
    comp_tbl = None
    m_comp = re.search(r"^Normalized composition for requested elements", full_text, re.MULTILINE)
    if m_comp is None:
        trilobite_logger.warning(
            "read_tops: 'Normalized composition' section not found in %s; composition fields will be None.",
            path.name,
        )
    else:
        comp_data_line = full_text[: m_comp.start()].count("\n") + 2  # skip hdr + col-hdr
        comp_tbl, _ = _read_indented_table(
            comp_data_line,
            ["number_fraction", "mass_fraction", "atomic_number", "element", "material_id"],
        )
        if len(comp_tbl) == 0:
            trilobite_logger.warning(
                "read_tops: composition header found but no data rows follow; composition fields will be None.",
            )
            comp_tbl = None
        else:
            trilobite_logger.debug(
                "read_tops: parsed %d-element composition (%s)",
                len(comp_tbl),
                ", ".join(comp_tbl["element"]),
            )

    # ---- Data blocks ----
    # Each block's column-header line contains both "Density" and "T=<value>".
    # Match all such lines in a single pass; the indented rows immediately below
    # each one form one opacity table at that temperature.
    _T_re = re.compile(r"\bDensity\b.*T=\s*([+-]?\d+\.?\d*[EeDd][+-]\d+)", re.IGNORECASE)

    T_keV_list: list = []
    rho_per_block: list = []
    ross_per_block: list = []
    planck_per_block: list = []
    nfree_per_block: list = []
    avsq_per_block: list = []

    for line_i, line in enumerate(ALL_LINES):
        m_T = _T_re.search(line)
        if m_T is None:
            continue
        T_kev = float(m_T.group(1).replace("D", "E").replace("d", "e"))
        blk, _ = _read_indented_table(line_i + 1, ["rho", "rosseland", "planck", "n_free", "av_sq_free"])
        if len(blk) == 0:
            trilobite_logger.warning("read_tops: data block at T=%.4g keV has no rows; skipping.", T_kev)
            continue
        T_keV_list.append(T_kev)
        rho_per_block.append(np.array(blk["rho"]))
        ross_per_block.append(np.array(blk["rosseland"]))
        planck_per_block.append(np.array(blk["planck"]))
        nfree_per_block.append(np.array(blk["n_free"]))
        avsq_per_block.append(np.array(blk["av_sq_free"]))
        trilobite_logger.debug("read_tops: T=%.4g keV — %d density rows", T_kev, len(blk))

    if not T_keV_list:
        raise ValueError(f"No opacity data blocks found in {path.name!r}.")

    trilobite_logger.debug(
        "read_tops: %d temperature blocks, T in [%.4g, %.4g] keV",
        len(T_keV_list),
        T_keV_list[0],
        T_keV_list[-1],
    )

    # ---- Assemble canonical density grid ----
    # Use the block with the most density rows as the reference.  Shorter
    # blocks are matched by log-space proximity and padded with NaN.
    ref_idx = int(np.argmax([len(r) for r in rho_per_block]))
    grid_rho = rho_per_block[ref_idx].copy()
    n_rho = len(grid_rho)
    n_T = len(T_keV_list)

    rosseland = np.full((n_T, n_rho), np.nan)
    planck = np.full((n_T, n_rho), np.nan)
    n_free_arr = np.full((n_T, n_rho), np.nan)
    av_sq_arr = np.full((n_T, n_rho), np.nan)

    _tol = np.min(np.diff(np.log(grid_rho))) * 0.4  # half smallest log-spacing

    for ti, (rho_b, rb, pb, nfb, asb) in enumerate(
        zip(rho_per_block, ross_per_block, planck_per_block, nfree_per_block, avsq_per_block)
    ):
        if len(rho_b) == n_rho and np.allclose(rho_b, grid_rho, rtol=1e-4):
            rosseland[ti] = rb
            planck[ti] = pb
            n_free_arr[ti] = nfb
            av_sq_arr[ti] = asb
        else:
            log_ref = np.log(grid_rho)
            for j, rho_j in enumerate(rho_b):
                dist = np.abs(np.log(rho_j) - log_ref)
                k = int(np.argmin(dist))
                if dist[k] <= _tol:
                    rosseland[ti, k] = rb[j]
                    planck[ti, k] = pb[j]
                    n_free_arr[ti, k] = nfb[j]
                    av_sq_arr[ti, k] = asb[j]

    # ---- Assemble result namespace ----
    ns = SimpleNamespace(
        grid_T=np.array(T_keV_list) * 1.1604518e7,  # keV to K
        grid_rho=grid_rho,
        rosseland=rosseland,
        planck=planck,
        n_free=n_free_arr,
        av_sq_free=av_sq_arr,
        elements=list(comp_tbl["element"]) if comp_tbl is not None else None,
        atomic_numbers=np.array(comp_tbl["atomic_number"], dtype=int) if comp_tbl is not None else None,
        number_fractions=np.array(comp_tbl["number_fraction"]) if comp_tbl is not None else None,
        mass_fractions=np.array(comp_tbl["mass_fraction"]) if comp_tbl is not None else None,
        material_ids=np.array(comp_tbl["material_id"], dtype=int) if comp_tbl is not None else None,
        title=title,
    )
    for attr in ("grid_T", "grid_rho", "rosseland", "planck", "n_free", "av_sq_free"):
        getattr(ns, attr).flags.writeable = False
    if comp_tbl is not None:
        for attr in ("atomic_numbers", "number_fractions", "mass_fractions", "material_ids"):
            getattr(ns, attr).flags.writeable = False

    trilobite_logger.debug(
        "read_tops: done — grid shape (%d T, %d rho), %.1f%% valid opacity values",
        n_T,
        n_rho,
        100.0 * np.isfinite(rosseland).sum() / rosseland.size,
    )
    return ns
